services:
  weaver-php:
    build: ./infra/docker/php
    container_name: weaver-php
    working_dir: /var/www/html
    env_file:
      - ./apps/weaver-laravel/.env
    environment:
      AUTO_COMPOSER_INSTALL: "true"
      AUTO_MIGRATE: "true"
      GITHUB_APP_PRIVATE_KEY_PATH: /run/secrets/github_app_private_key
  # APP_KEY is injected at runtime from /run/secrets/app_key by entrypoint.sh (load_secret); do NOT hardcode here.
    volumes:
      - ./apps/weaver-laravel:/var/www/html:cached
    secrets:
      - app_key
      - google_client_secret
      - microsoft_client_secret
      - db_password
      - github_app_private_key
      - source: github_app_private_key
        target: github_app_private_key
    depends_on:
      - weaver-db
    networks: [weaver-net]

  weaver-web:
    image: nginx:alpine
    container_name: weaver-web
    depends_on: [weaver-php]
    ports:
  - "8080:80"
  - "443:443"
  # - "8443:443"  # optional alt TLS
    volumes:
      - ./apps/weaver-laravel:/var/www/html:ro
  - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  - ./infra/certs:/etc/nginx/certs:ro
    networks: [weaver-net]

  weaver-db:
    image: mysql:8.0
    container_name: weaver-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: weaver
      MYSQL_USER: weaver
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
    ports:
      - "3306:3306"
    volumes:
      - weaver-db-data:/var/lib/mysql
    secrets:
      - db_password
      - mysql_root_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: [weaver-net]

  weaver-tunnel:
    image: ngrok/ngrok:latest
    container_name: weaver-tunnel
    depends_on: [weaver-web]
    env_file:
      - ./apps/weaver-laravel/.env
    command: /bin/sh -c "ngrok config add-authtoken $(cat /run/secrets/ngrok_authtoken) && ngrok http weaver-web:80"
    secrets:
      - ngrok_authtoken
    networks: [weaver-net]

volumes:
  weaver-db-data: {}

networks:
  weaver-net: {}

secrets:
  app_key:
    file: ./infra/secrets/app_key.txt
  google_client_secret:
    file: ./infra/secrets/google_client_secret.txt
  microsoft_client_secret:
    file: ./infra/secrets/microsoft_client_secret.txt
  db_password:
    file: ./infra/secrets/db_password.txt
  mysql_root_password:
    file: ./infra/secrets/mysql_root_password.txt
  ngrok_authtoken:
    file: ./infra/secrets/ngrok_authtoken.txt
  github_app_private_key:
  file: ./infra/secrets/github_app_private_key.pem
