name: Dynamic Static Builder
on:
  repository_dispatch:
    types: [dsb.new_article]

jobs:
  build_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch job artifact from Weaver
        env:
          WEAVER_BASE: ${{ secrets.WEAVER_BASE }}
          WEAVER_TOKEN: ${{ secrets.WEAVER_TOKEN }} # HMAC key for artifact endpoint
        run: |
          JOB_ID="${{ github.event.client_payload.job_id }}"
          TIMESTAMP=$(date +%s)
          SIGNATURE=$(echo -n "$TIMESTAMP" | openssl dgst -sha256 -hmac "$WEAVER_TOKEN" -binary | base64)
          curl -sS \
               -H "X-Timestamp: $TIMESTAMP" \
               -H "X-Signature: $SIGNATURE" \
               "$WEAVER_BASE/jobs/$JOB_ID/artifact" -o /tmp/article.json

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

    - name: Render and write files
        id: render
        run: |
      node tools/scripts/render.js /tmp/article.json
          # Extract metadata for commit message (output is set by render.js)
          echo "Files rendered successfully"

  - name: Create branch, commit, and PR
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "feat(content): add new content (job: ${{ github.event.client_payload.job_id }})"
          branch: "dsb/${{ github.event.client_payload.job_id }}"
          title: "Add content – job ${{ github.event.client_payload.job_id }}"
          body: |
            Automated content creation via Dynamic Static Builder
            
            Job ID: ${{ github.event.client_payload.job_id }}
            Branch: ${{ github.event.client_payload.branch }}
            Base Path: ${{ github.event.client_payload.base_path }}
          base: ${{ github.event.client_payload.branch }}
