name: Dynamic Static Builder
on:
  repository_dispatch:
    types: [dsb.new_article]

jobs:
  build_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch job artifact from Weaver
        env:
          WEAVER_BASE: ${{ secrets.WEAVER_BASE }}
          WEAVER_TOKEN: ${{ secrets.WEAVER_TOKEN }} # HMAC key or JWT private key
        run: |
          JOB_ID="${{ github.event.client_payload.job_id }}"
          curl -sS -H "Authorization: Bearer $WEAVER_TOKEN" \
               "$WEAVER_BASE/jobs/$JOB_ID/artifact" -o /tmp/article.json

      - name: Render and write files
        id: render
        run: |
          node scripts/render.js /tmp/article.json

      - name: Create branch, commit, and PR
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "feat(article): add ${{ fromJson(steps.render.outputs.meta).title }} (job: ${{ github.event.client_payload.job_id }})"
          branch: "dsb/${{ github.event.client_payload.job_id }}"
          title: "Add article – job ${{ github.event.client_payload.job_id }}"
          body: "Automated via Dynamic Static Builder"
          base: ${{ github.event.client_payload.branch }}
